### PR TITLE
upgrade to BioModels REST API

### PR DESCRIPTION
**Pull request by mglont**
Hi,

I've had a go at upgrading the BioModels integration in iBioSim. Please take a look and let me know your thoughts.

Cheers,
Mihai.

### CODE REVIEW

**Comment by cjmyers** [comment]
Hi,

I would like to test this, but I’m unsure how to do that.  Can I perhaps merge your code into a new branch in my repo somehow?  Sorry not a git guru.

Chris

**Comment by mglont** [comment]
Absolutely!

You could either clone my repo, checkout the branch and build it in the
usual way or you could try what you have suggested:

# add a reference to my GitHub fork
git remote add mihai https://github.com/mglont/iBioSim
# create a new branch from the current one (e.g. master)
git checkout -b biomodels-upgrade
# get my changes
git fetch mihai
# merge my branch into yours
git merge mihai/biomodelsREST
....test at will -- for instance run mvn test in the gui module

# delete your branch when you're done with it
git checkout master
git branch -d biomodels-upgrade

If you notice anything wrong in terms of design or functionality, please
let me know.

Cheers,
Mihai.

**Comment by cjmyers** [comment]
This seems to work well.  The fetching of descriptions used to be very slow, so we cached them.  Is this no longer necessary?

**Comment by cjmyers** [comment]
Actually, I prefer this code to be in iBioSim-dataModels, so I've moved it there and merged it into master.

**Pull request merged**
