### PR TITLE
L3 v2

### PR DESCRIPTION
**Pull request by cjmyers**
L3V2 is released.  Let's move iBioSim to L3V2.

### CODE REVIEW

**Comment by leandrohw** [comment]
This is not quite ready yet. Opening an existing model with reaction gives error about being invalid because of the fast flag. Simulating a model using reb2sac gave these:

Errors:
line 2: (99101 [Error]) The level and version specified for the document must be consistent with a valid published SBML specification.  These are Level 1, Versions 1 and 2; Level 2, Versions 1, 2, 3 and 4; and Level 3, Version 1.  If newer levels or versions of SBML now exist, you must update your version of libSBML.

line 2: (20103 [Error]) The <sbml> container element must declare the SBML Version using the attribute 'version', and this declaration must be consistent with the XML Namespace declared for the <sbml> element.
Reference: L3V1 Section 4.1

line 3: (10102 [Error]) An SBML XML document must not contain undefined elements or attributes in the SBML namespace. Documents containing unknown elements or attributes placed in the SBML namespace do not conform to the SBML specification.

Reference: L3V1 Section 4.1
 Element 'listOfLayouts' is not part of the definition of SBML Level 3 Version 2.

 :  : 	input file error

**Comment by cjmyers** [comment]
I’m not seeing either of these problems.  Are you sure you have the latest experimental libsbml and did you recompile reb2sac with this new library?

**Comment by leandrohw** [comment]
I’m using LibSBML 5.16.0, the one that was released this month. Is this the one you are using?

**Comment by cjmyers** [comment]
I’m still using 5.15.2.

Chris

**Comment by cjmyers** [comment]
Just downloaded and rebuilt reb2sac with 5.16.0 experimental for high sierra, and it works.

Did you remember to copy from /usr/local/bin/reb2sac to iBioSim/bin/reb2sac.mac64?

**Comment by cjmyers** [comment]
BTW: is there anything I need to do when I update libsbml to allow it to find the new libsbmlj.jar?

**Comment by leandrohw** [comment]
It seems to work now. I forgot to copy reb2sac to the iBioSim/bin directory. 
The new libsbmlj.jar can replace the new one in the lib directory.

**Pull request merged**
